#!/bin/bash -e
git clone http://dpdk.org/git/dpdk
cd dpdk
[[ -n $(git config user.name) ]] || git config user.name "nobody"
[[ -n $(git config user.email) ]] || git config user.email "nobody@nowhere"
git checkout -b stg_patched $(cat ../patches/series | head -1 | awk '{print $NF}')
stg init
stg import --series ../patches/series
